# Task 5

# Question 1 : XML 1 - Find the Score

You are given a valid XML document, and you have to print its score. The score is calculated by the sum of the score of each element. For any element, the score is equal to the number of attributes it has.

**Input Format**

The first line contains N, the number of lines in the XML document.
The next N lines follow containing the XML document.

**Output Format**

Output a single line, the integer score of the given XML document.

**Sample Input**

$6$<br>
$<feed xml:lang='en'>$<br>
$    <title>HackerRank</title>$<br>
$    <subtitle lang='en'>Programming challenges</subtitle>$<br>
$    <link rel='alternate' type='text/html'$<br> $href='http://hackerrank.com/'/>$<br>
$    <updated>2013-12-25T12:00:00</updated>$<br>
$</feed>$<br>

**Sample Output**

5<br>

**Explanation**<br>

The feed and subtitle tag have one attribute each - lang.<br>
The title and updated tags have no attributes.<br>
The link tag has three attributes - rel, type and href.<br>

So, the total score is 1 + 1 + 3 = 5.<br>

There may be any level of nesting in the XML document. To learn about XML parsing, refer here.<br>

NOTE: In order to parse and generate an XML element tree, use the following code:<br>

> import xml.etree.ElementTree as etree <br>
> tree = etree.ElementTree(etree.fromstring(xml))<br>
Here, XML is the variable containing the string.<br>
Also, to find the number of keys in a dictionary, use the len function:<br>

> dicti = {'0': 'This is zero', '1': 'This is one'}<br>
> print (len(dicti))<br>


2


In [7]:
import xml.etree.ElementTree as etree
numlines = int(input())
XML = ''
for _ in range(numlines):
    XML += input()
    
root = etree.fromstring(XML)
print (sum([len(i.attrib) for i in root.iter()]))

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
5


# Question 2 : XML2 - Find the Maximum Depth

You are given a valid XML document, and you have to print the maximum level of nesting in it. Take the depth of the root as 0.

**Input Format**

The first line contains $N$, the number of lines in the XML document.
The next $N$ lines follow containing the XML document.

**Output Format**

Output a single line, the integer value of the maximum level of nesting in the XML document.

**Sample Input**

$6$<br>
$<feed xml:lang='en'>$<br>
$    <title>HackerRank</title>$<br>
$    <subtitle lang='en'>Programming challenges</subtitle>$<br>
$    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>$<br>
$    <updated>2013-12-25T12:00:00</updated>$<br>
$</feed>$<br>

**Sample Output**

1

**Explanation**

Here, the root is a feed tag, which has depth of O.
The tags title, subtitle, link and updated all have a depth of 1.

Thus, the maximum depth is 1.

In [10]:
maxdepth = 0
def depth(elem, level):
    global maxdepth
    level += 1
    if (maxdepth < level):
        maxdepth = level
    for child in elem:
        depth(child, level)
        
if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
1


# Question 3 : Standardize Mobile Number Using Decorators

Let's dive into decorators! You are given  mobile numbers. Sort them in ascending order then print them in the standard format shown below:


> +91 xxxxx xxxxx

The given mobile numbers may have +91,91 or O written before the actual 10 digit number. Alternatively, there may not be any prefix at all.

**Input Format**

The first line of input contains an integer N, the number of mobile phone numbers.
N lines follow each containing a mobile number.

**Output Format**

Print N mobile numbers on separate lines in the required format.

**Sample Input**

3<br>
07895462130<br>
919875641230<br>
9195969878<br>

**Sample Output**

+91 78954 62130<br>
+91 91959 69878<br>
+91 98756 41230<br>

**Concept**

Like most other programming languages, Python has the concept of closures. Extending these closures gives us decorators, which are an invaluable asset. You can learn about decorators in 12 easy steps here.
To solve the above question, make a list of the mobile numbers and pass it to a function that sorts the array in ascending order. Make a decorator that standardizes the mobile numbers and apply it to the function.

In [11]:
l = [input() for _ in range(int(input()))]

def wrapper(f):
    def phone(l):
        f(["+91 "+c[-10:-5]+" "+c[-5:] for c in l])
    return phone

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

sort_phone(l)

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


# Question 4 : Decorators 2 - Name Directory

Let's use decorators to build a name directory! You are given some information about N people. Each person has a first name, last name, age and sex. Print their names in a specific format sorted by their age in ascending order i.e. the youngest person's name should be printed first. For two people of the same age, print them in the order of their input.

For Henry Davids, the output should be:

> Mr. Henry Davids

For Mary George, the output should be:

> Ms. Mary George

**Input Format**

The first line contains the integer N, the number of people.
N lines follow each containing the space separated values of the first name, last name, age and sex, respectively.

**Constraints**

1 $\leq$ N $\leq$ 10

**Output Format**

Output N names on separate lines in the format described above in ascending order of age.

**Sample Input**

3<br>
Mike Thomson 20 M<br>
Robert Bustle 32 M<br>
Andria Bustle 30 F<br>

**Sample Output**

Mr. Mike Thomson<br>
Ms. Andria Bustle<br>
Mr. Robert Bustle<br>

**Concept**

For sorting a nested list based on some parameter, you can use the itemgetter library. You can read more about it here.

In [17]:
import operator

people = [input().split() for i in range(int(input()))]

def person_lister(f):
    def inner(people):
        return [f(person) for person in sorted(people, key=operator.itemgetter(2))]
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

print(*name_format(people), sep='\n')


3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


# Question 5 : Words Score

In this challenge, the task is to debug the existing code to successfully execute all provided test files.

Consider that vowels in the alphabet are a, e, i, o, u and y.

Function score_words takes a list of lowercase words as an argument and returns a score as follows:

The score of a single word is 2 if the word contains an even number of vowels. Otherwise, the score of this word is 1. The score for the whole list of words is the sum of scores of all words in the list.

Debug the given function score_words such that it returns a correct score.

Your function will be tested on several cases by the locked template code.

**Input Format**

The input is read by the provided locked code template. In the first line, there is a single integer  denoting the number of words. In the second line, there are n space-separated lowercase words.

**Constraints**

1 $\leq$ n $\leq$ 20

Each word has at most 20 letters and all letters are English lowercase letters

**Output Format**

The output is produced by the provided and locked code template. It calls function score_words with the list of words read from the input as the argument and prints the returned score to the output.

**Sample Input 0**

2 <br>
hacker book<br>

**Sample Output 0**

4

**Explanation 0**

There are two words in the input: hacker and book. The score of the word hacker is 2 because it contains an even number of vowels, i.e. 2 vowels, and the score of book is 2 for the same reason. Thus the total score is.

2 + 2 = 4.

**Sample Input 1**

3<br>
programming is awesome<br>

**Sample Output 1**<br>

4

**Explanation 1**

There are 3 words in the input: programming, is and awesome. The score of programming is 1 since it contains 3 vowels, an odd number of vowels. The score of is is also 1 because it has an odd number of vowels. The score of awesome is  since it contains  vowels, an even number of vowels. Thus, the total score is 

1 + 1 + 2 = 4.

In [18]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

import re
from functools import reduce

def score_words(words): 
    return reduce(lambda x, y: x+y, 
       [2 if (len(re.findall('[aeiouy]',a))%2 == 0) else 1 for a in words], 0)

n = int(input())
words = input().split()
print(score_words(words))

2
hacker book
4


# Question 6 : Arrays

**Task**

You are given a space separated list of numbers. <br>
Your task is to print a reversed NumPy array with the element type float.<br>

**Input Format**

A single line of input containing space separated numbers.

**Output Format**

Print the reverse NumPy array with type float.

**Sample Input**

1 2 3 4 -8 -10
<br>
**Sample Output**

[-10.  -8.   4.   3.   2.   1.]

In [22]:
import numpy

print (numpy.flipud(numpy.array(input().split(),float)))

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Question 7 : Shape and Reshape

**Task**

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

**Input Format**

A single line of input containing  space separated integers.

**Output Format**

Print the 3X3 NumPy array.

**Sample Input**

1 2 3 4 5 6 7 8 9<br>

**Sample Output**

[[1 2 3]<br>
 [4 5 6]<br>
 [7 8 9]]<br>

In [23]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 8 : Default Arguments

In this challenge, the task is to debug the existing code to successfully execute all provided test files.

Python supports a useful concept of default argument values. For each keyword argument of a function, we can assign a default value which is going to be used as the value of said argument if the function is called without it. For example, consider the following increment function:

> def increment_by(n, increment=1):<br>
>     return n + increment<br>


The functions works like this:<br>

> increment_by(5, 2)<br>
7
> increment_by(4)<br>
5
>

Debug the given function print_from_stream using the default value of one of its arguments.

The function has the following signature:

> def print_from_stream(n, stream)

This function should print the n first  values returned by get_next() method of stream object provided as an argument. Each of these values should be printed in a separate line.

Whenever the function is called without the stream argument, it should use an instance of EvenStream class defined in the code stubs below as the value of stream.

Your function will be tested on several cases by the locked template code.

**Input Format**

The input is read by the provided locked code template. In the first line, there is a single integer q denoting the number of queries. Each of the following q lines contains a stream_name followed by integer n, and it corresponds to a single test for your function.

**Constraints**

1 $\leq$ q $\leq$ 100 <br>

1 $\leq$ n $\leq$ 10


**Output Format**

The output is produced by the provided and locked code template. For each of the queries (stream_name, n), if the stream_name is even then print_from_stream(n) is called. Otherwise, if the stream_name is odd, then print_from_stream(n, OddStream()) is called.

**Sample Input 0**

3<br>
odd 2<br>
even 3<br>
odd 5<br>

**Sample Output 0**

1<br>
3<br>
0<br>
2<br>
4<br>
1<br>
3<br>
5<br>
7<br>
9<br>

**Explanation 0**

There are 3 queries in the sample.

In the first query, the function print_from_stream(2, OddStream()) is exectuted, which leads to printing values 1 and 3 in separated lines as the first two non-negative odd numbers.

In the second query, the function print_from_stream(3) is exectuted, which leads to printing values 2,4 and 6 in separated lines as the first three non-negative even numbers.

In the third query, the function print_from_stream(5, OddStream()) is exectuted, which leads to printing values 1,3,5,7 and 9 in separated lines as the first five non-negative odd numbers.

In [27]:
class EvenStream(object):

    def __init__(self):
        self.current = 0

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

class OddStream(object):

    def __init__(self):
        self.current = 1

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

def print_from_stream(n, stream=None):

    if stream is None:
        stream = EvenStream()

    for _ in range(n):
        print (stream.get_next())

queries = int(input())

for _ in range(queries):
    stream_name, n = input().split()
    n = int(n)
    if stream_name == "even":
        print_from_stream(n)
    else:
        print_from_stream(n, OddStream())


3
odd 2
1
3
even 3
0
2
4
odd 5
1
3
5
7
9


# Question 9 : Transpose and Flatten

**Task**

You are given a N X M integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.

**Input Format**

The first line contains the space separated values of N and M.
The next  lines contains the space separated elements of  columns.

**Output Format**

First, print the transpose array and then print the flatten.

**Sample Input**

2 2<br>
1 2<br>
3 4<br>

**Sample Output**

[[1 3]<br>
 [2 4]]<br>
[1 2 3 4]<br>

In [28]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Question 10 : Concatenate

**Task**

You are given two integer arrays of size N X P and M X P ( N & M are rows, and P is the column). Your task is to concatenate the arrays along axis O.

**Input Format**

The first line contains space separated integers N , M and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the P columns.

**Output Format**

Print the concatenated array of size (N + M) X P.

**Sample Input**

4 3 2<br>
1 2<br>
1 2 <br>
1 2<br>
1 2<br>
3 4<br>
3 4<br>
3 4 <br>

**Sample Output**

[[1 2]<br>
 [1 2]<br>
 [1 2]<br>
 [1 2]<br>
 [3 4]<br>
 [3 4]<br>
 [3 4]] <br>

In [30]:
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))


4 3 2
1 2
1 2 
1 2 
1 2 
3 4 
3 4 
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Question 11 : Zeros and Ones

**Task**

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

**Input Format**

A single line containing the space-separated integers.

**Constraints**

1 $\leq$ each integer $\leq$ 3 <br>

**Output Format**

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

**Sample Input 0**

3 3 3 <br>

**Sample Output 0**

[[[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]<br>

 [[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]<br>

 [[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]]<br>
[[[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]<br>

 [[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]<br>

 [[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]]<br>

**Explanation 0**

Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.

In [31]:
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Question 12 : Eye and Identity

**Task**

Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.

**Input Format**

A single line containing the space separated values of N and M.
N denotes the rows.
M denotes the columns.

**Output Format**

Print the desired N X M array.

**Sample Input**

3 3<br>

**Sample Output**

[[ 1.  0.  0.]<br>
 [ 0.  1.  0.]<br>
 [ 0.  0.  1.]]<br>

In [32]:
m,n = (map(int, input().split(" ")))
print(np.eye(m,n))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 13 : Array Mathematics

**Task**

You are given two integer arrays,  and  of dimensions N X M.
Your task is to perform the following operations:

Add (A + B)
Subtract (A - B)
Multiply (A * B)
Integer Division (A / B)
Mod (A % B)
Power (A ** B)

**Input Format**

The first line contains two space separated integers, N and M.
The next N lines contains M space separated integers of array A.
The following N lines contains M space separated integers of array B.

**Output Format**

Print the result of each operation in the given order under Task.

**Sample Input**

1 4 <br>
1 2 3 4<br>
5 6 7 8<br>

**Sample Output**

[[ 6  8 10 12]]<br>
[[-4 -4 -4 -4]]<br>
[[ 5 12 21 32]]<br>
[[0 0 0 0]]<br>
[[1 2 3 4]]<br>
[[    1    64  2187 65536]] <br>
Use // for division in Python 3.

In [33]:
import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], 
             dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')


1 4 
1 2 3 4 
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Question 14 : Floor, Ceil and Rint

**Task**

You are given a 1-D array, A. Your task is to print the $floor, ceil and rint$  of all the elements of A.

**Input Format**

A single line of input containing the space separated elements of array A.

**Output Format**

On the first line, print the  of A. <br>
On the second line, print the  of A.<br>
On the third line, print the  of A.<br>

**Sample Input**

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9<br>

**Sample Output**

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]<br>
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]<br>
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]<br>

In [34]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Question 15 : Sum and Prod

**Task**

You are given a 2-D array with dimensions N X M.
Your task is to perform the $sum$ tool over axis 0 and then find the $product$ of that result.

**Input Format**

The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

Compute the sum along axis 0. Then, print the product of that sum.

**Sample Input**

2 2<br>
1 2<br>
3 4<br>

**Sample Output**

24<br>

**Explanation**

The sum along axis 0 = [4 6]<br>
The product of this sum = 24

In [35]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2 
1 2 
3 4
24


# Question 16 : Min and Max

**Task**

You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 1 and then find the max of that.

**Input Format**

The first line of input contains the space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

Compute the min along axis 1 and then print the max of that result.

**Sample Input**

4 2<br>
2 5<br>
3 7<br>
1 3<br>
4 0<br>

**Sample Output**

3<br>

**Explanation**

The min along axis 1 = [2,3,1,0] 
The max of  [2,3,1,0] = 3

In [36]:
import numpy as np
print(np.max(np.min(np.array([input().split() 
     for _ in range(int(input().split()[0]))],int),axis=1)))

4 2 
2 5 
3 7 
1 3 
4 0
3


# Question 17 : Mean, Var, and Std

**Task**

You are given a 2-D array of size N X M.
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis $None$

**Input Format**

The first line contains the space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

First, print the mean.<br>
Second, print the var.<br>
Third, print the std.<br>

**Sample Input**

2 2<br>
1 2<br>
3 4<br>

**Sample Output**

[ 1.5  3.5]<br>
[ 1.  1.]<br>
1.11803398875

In [37]:
import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
print(np.std(b))

2 2
1 2 
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Question 18 : Dot and Cross


**Task**

You are given two arrays A and B. Both have dimensions of N X N.
Your task is to compute their matrix product.

**Input Format**

The first line contains the integer N.
The next N lines contains N space separated integers of array A.
The following N lines contains N space separated integers of array B.

**Output Format**

Print the matrix multiplication of A and B.

**Sample Input**

2<br>
1 2<br>
3 4<br>
1 2<br>
3 4<br>

**Sample Output**

[[ 7 10]<br>
 [15 22]]<br>

In [38]:
from __future__ import print_function
import numpy
n=int(input())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
m = numpy.dot(a,b)
print (m)

2 
1 2 
3 4 
1 2 
3 4
[[ 7 10]
 [15 22]]


# Question 19 : Inner and Outer

**Task**

You are given two arrays: A and B.
Your task is to compute their inner and outer product.

**Input Format**

The first line contains the space separated elements of array A.
The second line contains the space separated elements of array B.

**Output Format**

First, print the inner product.
Second, print the outer product.

**Sample Input**

0 1<br>
2 3<br>

**Sample Output**

3<br>
[[0 0]<br>
 [2 3]]<br>

In [39]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1 
2 3
3
[[0 0]
 [2 3]]


# Question 20 : Polynomials

**Task**

You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.

**Input Format**

The first line contains the space separated value of the coefficients in P.
The second line contains the value of x.

**Output Format**

Print the desired value.

**Sample Input**

1.1 2 3<br>
0<br>

**Sample Output**

3.0

In [46]:
n = list(map(float,input().split()));
m = input();
print(numpy.polyval(n,int(m)));

1.1 2 3
0
3.0


# Question 21 : Linear Algebra

**Task**

You are given a square matrix A with dimensions NXN. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

**Input Format**

The first line contains the integer N.
The next N lines contains the N space separated elements of array A.

**Output Format**

Print the determinant of A.

**Sample Input**

2<br>
1.1 1.1<br>
1.1 1.1<br>

**Sample Output**

0.0

In [47]:
import numpy
print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) for _ in range(int(input()))])),2))

2 
1.1 1.1 
1.1 1.1
0.0
